from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from flavours.models import Flavour
from toppings.models import Topping
from orders.models import Order, OrderItem
import random

User = get_user_model()

class Command(BaseCommand):
    help = "Seed the database with fake users, flavours, toppings, and orders."

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS("🌱 Starting data seeding..."))

        # --- Users ---
        if not User.objects.exists():
            for i in range(1, 6):
                user = User.objects.create_user(
                    username=f"user{i}",
                    password="password123",
                    email=f"user{i}@example.com"
                )
                self.stdout.write(f"Created user: {user.username}")
        else:
            self.stdout.write("Users already exist — skipping.")

        users = list(User.objects.all())

        # --- Flavours ---
        flavour_data = [
            ("Vanilla", "Classic creamy vanilla flavour", 2.50),
            ("Chocolate", "Rich chocolate ice cream", 2.75),
            ("Strawberry", "Sweet and fruity strawberry", 2.60),
            ("Mint", "Refreshing mint flavour", 2.40),
            ("Cookies & Cream", "Crunchy cookie pieces in cream", 2.90),
        ]

        if not Flavour.objects.exists():
            for name, desc, price in flavour_data:
                Flavour.objects.create(name=name, description=desc, price=price)
            self.stdout.write("Added sample flavours.")
        else:
            self.stdout.write("Flavours already exist — skipping.")

        flavours = list(Flavour.objects.all())

        # --- Toppings ---
        topping_data = [
            ("Sprinkles", 0.50),
            ("Chocolate Chips", 0.75),
            ("Caramel Sauce", 0.80),
            ("Whipped Cream", 0.60),
            ("Crushed Nuts", 0.70),
        ]

        if not Topping.objects.exists():
            for name, price in topping_data:
                Topping.objects.create(name=name, price=price)
            self.stdout.write("Added sample toppings.")
        else:
            self.stdout.write("Toppings already exist — skipping.")

        toppings = list(Topping.objects.all())

        # --- Orders ---
        for user in users:
            for _ in range(random.randint(2, 4)):  # 2–4 orders per user
                order = Order.objects.create(customer=user, notes="Autogenerated order")
                for _ in range(random.randint(1, 3)):  # 1–3 items per order
                    flavour = random.choice(flavours)
                    quantity = random.randint(1, 3)
                    item = OrderItem.objects.create(order=order, flavour=flavour, quantity=quantity)
                    item.toppings.set(random.sample(toppings, random.randint(0, 3)))

        self.stdout.write(self.style.SUCCESS("✅ Database seeded with sample data!"))
